# Generated by Django 5.0.4 on 2026-04-14 18:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('forecast_date', models.DateField()),
                ('meal_period', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20)),
                ('expected_covers', models.PositiveIntegerField()),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-forecast_date', 'meal_period'],
                'unique_together': {('forecast_date', 'meal_period')},
            },
        ),
        migrations.CreateModel(
            name='StaffingRequirement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('front_of_house', models.PositiveIntegerField()),
                ('back_of_house', models.PositiveIntegerField()),
                ('management', models.PositiveIntegerField(default=1)),
                ('forecast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staffing', to='forecasting.demandforecast')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
