# Generated by Django 5.0.4 on 2026-04-14 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_forecastaccuracy'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='forecastaccuracy',
            name='feedback_fo_date_903251_idx',
        ),
    ]
