# Generated by Django 5.0.4 on 2026-04-14 18:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('litre', 'Litres'), ('piece', 'Pieces'), ('dozen', 'Dozen')], max_length=20)),
                ('per_dish_quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('shelf_life_days', models.PositiveIntegerField()),
                ('supplier_lead_time_days', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['shift_date'], name='operations__shift_d_98ddcf_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['role'], name='operations__role_114238_idx'),
        ),
    ]
