# Generated by Django 5.0.4 on 2026-04-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_ingredient_shift_operations__shift_d_98ddcf_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='per_dish_quantity',
            new_name='default_quantity_per_dish',
        ),
    ]
